### ISSUE TITLE
Should number in input NDEF message be mapped to JSON type?

### ISSUE THREAD

**Issue by DonnaWuDongxia** [w3c-cg/web-nfc#228]
As Reilly pointed out in the code review[[1]] that: According to the specification[[2]] a Number should be expressed as a JSON type record. Also, since JSON cannot represent Infinity and -Infinity as much as it cannot represent NaN(NOTE-4 in 24.5.2 JSON.stringify section in [[3]]) the typedef should be updated to use "double" rather than "unrestricted double".

So here is the question: for NFCWriter::push(), if one of the input record has just a double number as its data feild, without "recordType" feild nor mediaType feild, should we map it to NDEFRecordType::text or NDEFRecordType::json?
According to "create Web NFC message " section in spec[[4]], NDEFRecordType::text will be deduced, but there is no possible number value in the "NDEFRecord data" column in data-mapping[[1]].

[1]: https://chromium-review.googlesource.com/c/chromium/src/+/1628587/6/third_party/blink/renderer/modules/nfc/nfc.cc#104
[2]: https://w3c.github.io/web-nfc/#data-mapping;
[3]: http://www.ecma-international.org/publications/files/ECMA-ST/Ecma-262.pdf;
[4]: https://w3c.github.io/web-nfc/#creating-web-nfc-message

**Comment by kenchris** [comment]
To be honest, I am not sure how big a use-case it is writing just numbers and as you can surely do that manually and store it as you want.

I believe we have the support because it is valid in/as JSON- which then means that it makes sense to handle as JSON would handle it

![image](https://user-images.githubusercontent.com/1101339/62458764-09d18880-b77e-11e9-8f83-0e81429f2280.png)

![image](https://user-images.githubusercontent.com/1101339/62458883-4dc48d80-b77e-11e9-9148-4f5cee4cce50.png)

On the other hand, that seems fine when defining that we want to store as JSON, but as we handle text automatically (there is a Text RDT in NFC, but no number one... ) that seems a bit weird.

In a way I think we should not allow storing numbers unless we are storing JSON.

**Comment by kenchris** [comment]
@reillyeon?

**Comment by reillyeon** [comment]
I agree. Numbers should be handled as part of JSON.
