### ISSUE TITLE
"typedef DOMString NDEFRecordType" is expected to be case sensitive or not?

### ISSUE THREAD

**Issue by leonhsl** [w3c-cg/web-nfc#331]
I feel the record type string should always be treated as case insensitive, 
  External type strings: of course we treat them as case insensitive, based on nfc forum spec.
  other type strings:  '`TExt`', '`teXT`'  ==> '`text`', '`JSON`', '`Json`', '`jSoN`' ==> '`json`', etc.

WDYT? If it makes sense to you, we'd better put a sentence describing the 'case insensitive' thing around https://w3c.github.io/web-nfc/#the-ndefrecordtype-string.

Then, for simple impl in Chromium, I'd consider transforming the input NDEFRecordType (`NDEFRecordInit#recordType`, `NFCScanOptions#recordType`) to lower case in the first place.

**Comment by kenchris** [comment]
Web APIs are case sensitive, thus "TeXT" should be rejected as it is not equal to "text".

The external type (after :) is case insensitive as per NFC specs.

URLs (the part before :) is usually case insensitive, but would be good to check whether NFC specs treads it as such

**Comment by kenchris** [comment]
![image](https://user-images.githubusercontent.com/1101339/64151413-9b3e2400-ce2a-11e9-991e-7ca2547884b9.png)

We should be able to provide the URL as on the left side in this table and use that algorithm to derive the right side

That algorithm already takes care of lower-casing, see EXAMPLE.com which becomes example.com

We might need to refer to this in the spec - also test cases would be useful

**Comment by leonhsl** [comment]
Got it, first I'd make `NDEFRecord` ctor throw a TypeError in case of the record type being provided as '`TeXT`' alike.

**Comment by leonhsl** [comment]
Let me take an example to ask the question:
If users create an external record with NDEFRecordInit#recordType being '`www.example.com:xyz`', for pushing, do you mean that we need to transform the type to '`example.com:xyz`'? i.e. using its registrable domain instead?

**Comment by leonhsl** [comment]
If the answer is yes, `null` registrable domain would be a problem, since Android SDK says [1] that both domain and type should be non-empty.

> The unchecked exception IllegalArgumentException will be thrown if the domain and type have serious problems, for example if either field is empty, so always catch this exception if you are passing user-generated data into this method.

[1] https://developer.android.com/reference/android/nfc/NdefRecord.html#createExternal(java.lang.String,%20java.lang.String,%20byte%5B%5D)

**Comment by kenchris** [comment]
We just shouldn't allow those, like github.io which is registered... this means that I can use kenchris.github.io:shoppingitem

**Comment by leonhsl** [comment]
`xyz.github.io`'s registrable domain is still the same `xyz.github.io`, so it does not matter on the decision whether we transform the type to its registrable domain or not.

My question was: do we need to transform 'www.example.com:xyz' to 'example.com:xyz'?

And another new question: from your last comment, it seems to me that the impl should throw a TypeError for the user input `github.io` because it's an already registered one?

The spec needs to be clear about this.

**Comment by kenchris** [comment]
Yes, because that is the registered domain, and it is common that companies use a lot of subdomains like blah.intel.com and phone.intel.com etc and they should all be registered as intel.com. Many sites also work whether you add www. or not and it would be bad if I wrote a tag when on www. and then not being able to read it when I didn't add www.

**Comment by kenchris** [comment]
I am totally ok with adding the TypeError exception

**Comment by reillyeon** [comment]
Are we sure that we want to rely on the Public Suffix List in this specification?

https://github.com/sleevi/psl-problems

**Comment by sleevi** [comment]
Good question, @reillyeon . I got mentioned to this issue from https://chromium-review.googlesource.com/c/chromium/src/+/1791533 , which came from some confusion around Chromium's PSL API.

It's definitely better to *not* rely on the PSL here, and hopefully having shared that rant externally may help explain why :)

For all new features, we should be working to make sure they follow the Same Origin Policy. While I'm not too familiar with NFC, this does seem like it would create a side-channel that allows two different origins (`blah.intel.com` and `shop.intel.com`, for example) to exchange information, which is a bit opposite of where the Web is going, as it tries to move to private-by-default. Cookies remain the tricky part, but the more features we have to retrofit beyond eTLD+1, the harder it becomes to make a better, safer, web.

On the topic of safety, as that post calls out, using eTLD+1 is frequently "insecure by default". Accidentally leaking cookies, or allowing cookies to be pinned, is definitely bad, but it seems like it would be far worse to allow cross-origin reading of NFC state if someone didn't add themselves to the PSL.

Even if they did add themselves to the PSL, this creates cross-browser compatibility issues; if you were to try to move the NFC device from one browser to another, and they had different versions of the PSL, tags created in one might not be readable in another. Cookie sharing between browsers is very uncommon - usually only when/if you switch browsers and import settings from the old browsers - but I imagine using the same NFC device between different browsers, and even different devices, is an important goal!

If you're looking for stable, interoperable identifiers, then using the fully qualified domain name (... origin) is definitely the way to go here.

Happy to help however I can, @leonhsl and @kenchris, and apologies if I've misunderstood the feature or the motivations. If it's easier to setup a video chat or phone call or something for a higher bandwidth discussion, do let me know. I will try and follow up with @reillyeon to make sure I haven't missed anything.

**Comment by zolkis** [comment]
1. Related to the original question, IMHO we should follow the constraints of the NDEF specs.

The NDEF Record Type Definition spec says

> Two External Type Names MUST be compared in a **case-insensitive** manner. Example:
“example.com:foobar”
“Example.com:foobar”
“Example.COM:Foobar”
“eXaMpLe.CoM:fOoBaR”
The four examples above represent all the same External Type Name.

In turn, for Well Known Types 

> Two Well Known Types (including Global and Local Names) MUST be compared on a **case-
sensitive**, character-by-character basis. In other words, two Well Known Types MUST be
considered equal if and only if their binary representations are identical.

For payload identifiers, the NDEF spec says

> By providing a payload identifier, it becomes possible for other payloads supporting URI-based linking technologies to refer to that payload. NDEF does not mandate any particular linking mechanism or format but leaves this to the user application to define in the language it prefers.

The spec notes that non-standard values are "discouraged", i.e. they are not guaranteed to work, but don't require special validation from NFC HW. Also, as mentioned elsewhere, encoding is left to the NDEF application, in our case the implementation (or the underlying Android implementation). 

We are free to define constraints in Web NFC, they will be application-level constrains from NDEF point of view.

2. Regarding the same-origin policy, 

Content that is written by a web page to a tag using the Web NFC API becomes public knowledge, as Kenneth said once it's like a post-it note.

There is no way to ensure that an origin read from a tag was actually written by that origin using the 
Web NFC API, so implementations cannot apply same-origin policy for reading tags.

For peer push implementations could enforce that the exchanged content has the same origin on both devices.

**Comment by sleevi** [comment]
@zolkis If I’m understanding correctly, and any origin can read these tags and there is no security model associated with that data, there is no technical reason not to use the fully qualified domain. Is that correct?

**Comment by kenchris** [comment]
Except we are writing the current domain by default, so and many sites work like example.com and www.example.com so depending on what exact url you used to access the site, a different url would be written

**Comment by sleevi** [comment]
Yea, that seems to be the correct and desired behavior, and aligns with
much of the Web Platform, which uses the origin for features and
permissions.

Why would that create an issue? The website can make sure the “correct” or
“expected” origin by making sure the user is on the correct page, same as
they do today, right?

**Comment by zolkis** [comment]
Right, when we write the domain it's a convenience feature to apps, but not a security feature. 
Once implementations write a tag, there is no guarantee some other NFC app will not read the tag and overwrite the data with whatever they please.

We could write fully qualified domains, yes. NDEF allows abbreviations in URI records that are described in the NDEF URI spec, but that should be internal optimization to NFC - our spec could impose the constraint that Web NFC apps should write and get fully qualified URLs (but implementations could abbreviate them according to the NDEF spec). 
This would simplify the Web NFC spec since all the tricks become encapsulated by implementations and our algo's would not need to refer to tables defined in the NDEF spec.

**Comment by sleevi** [comment]
I don't think offering that implementation flexibility would be good - it
would definitely create interoperability problems, particularly if using
the PSL. I would think implementations MUST use the FQDN.

For the convenience side, it seems like the same solutions used with
postMessage work. The web page receives the full origin, and if they'd like
to allow messages (or tags) from subdomains, they can check that the origin
== '.example.com'

>

**Comment by kenchris** [comment]
@zolkis I dont think that the ID field compresses the URLs like the url records but I might be wrong.

Can you make the spec changes and add good examples showing the suggestions that @sleevi made?

For the external records, the NFC specs does have some text saying to basically use the registered domain and not fully qualified domain names, but we can just add that as a note because I dont see the NFC spec disallowing people from doing whatever they want to do

**Comment by kenchris** [comment]
> The NDEF Record Type Definition spec says
> 
> > Two External Type Names MUST be compared in a **case-insensitive** manner. Example:
> > “example.com:foobar”
> > “Example.com:foobar”
> > “Example.COM:Foobar”
> > “eXaMpLe.CoM:fOoBaR”
> > The four examples above represent all the same External Type Name.

Meaning that we can allow only lower case values and can expose the value as lower case only.

**Comment by leonhsl** [comment]
So I'll make our impl go with FQDN.

About this, by my understanding of the **case-insensitive** thing described in NFC spec, should we just allow all lower and higher case characters and leave users to care about the case comparision things? Can you clarify more for Web NFC spec to add such a constraint?
 
> Meaning that we can allow only lower case values and can expose the value as lower case only.

**Comment by kenchris** [comment]
- We should only allow lowercase input
- When we read from tags, we convert to lower case so all comparisons will be on lowercase values
- When we expose the values (output) they are also lowercased

**Comment by leonhsl** [comment]
Sorry I was asking why... Is it due to some special reason for adding such an extra constraint?

**Comment by leonhsl** [comment]
Except for `The NDEFRecordType string`, there're other places also using `registrable domain` in Web NFC spec, do we need to rethink about them with the PSL problem we're now clear of?

**Comment by kenchris** [comment]
I don't see any reason to write the url as anything but lowercase when it is compared lower case as well - that is totally allowed by the spec.

The value is very similar to an enum but isn't an enum because you can add urls for external record types, and the default naming guideline from the TAG is that such enums should be lowercase:

https://w3ctag.github.io/design-principles/#casing-rules

**Comment by zolkis** [comment]
Small recap. NFC specs says comparisons should be done case-insensitive.

Therefore apps can use mixed case without issues, there is no constraint from NFC.

However, the Web NFC spec (as an NFC _app_) can impose policies like:
1. We allow writing only FQDN and be specific in the spec on how we do comparisons and what is left to applications to figure out about how to specify filtering URL patterns.
2. We lowercase the input from NDEF messages we read, use that in comparisons and present that to the web page/apps.
3. We don't lowercase input from NDEF messages we read, use case-insensitive comparison where the NDEF specs dictate, but expose the unchanged content to web pages/apps.
4. We only accept lowercase input from web pages.
5. We silently convert input from web pages to lowercase.
6. We write input from web pages as it is (consistent with 1).
(7. We can use encoding that is best for the web, an issue discussed earlier.)

My own opinion: 
- for policy 1, we got useful input from @sleevi (thanks!) that we must have this (with reasons/examples to be exposed in the spec).
- for 2+4, [suggested](https://github.com/w3c/web-nfc/issues/331#issuecomment-531616728) by Kenneth, I am neutral, but if anything, I find it slightly inconsistent, since if we silently lowercase output, why not _silently_ lowercase input as well (policy 5)? So 2+5 would be more consistent. This might simplify things for implementation and developers who don't read the spec, just intuitively want to do something with Web NFC API as it is, write mixed case to tags and wonder why do they get a match when they (for instance) have expected case-sensitive comparisons. 2+5 would fix that, they'd soon realize that we are the knights who say _lowercase_ :).

The alternative to 2+4 (or 2+5) would be case-transparency (3+6): only the comparisons done case-insensitive where the NDEF specs require it, and we are clear about this in the spec, but we don't change content.

IMHO 1+3+6 would be a more consistent set of policies, so there my vote goes. I am open to corrections/suggestions.

**Comment by kenchris** [comment]
We could lowercase the urls, but I don't want to accept the other values like "JsOn"

**Comment by leonhsl** [comment]
+1 to 1+3+6

I think we're still discussing the external type string, right? First, it does not involve with any **urls**, second, `example.com:JsOn` should be OK, no matter we go with 2+4 or 3+6, but of course `JsOn` is **NOT** OK, because it's not equal to `json` which is a well-known record type (not external record type) and should be always treated in a case-sensitive way from a previous comment.

> Web APIs are case sensitive, thus "TeXT" should be rejected as it is not equal to "text".

**Comment by leonhsl** [comment]
Could we move forward here to define a clear/exact naming rule for external types in spec? We want to implement based on the correct definition to address any potential security concerns.

**Comment by leonhsl** [comment]
#350 is also focused on the naming rules for external types.

**Comment by zolkis** [comment]
OK, I propose we move on with 1+3+6 that you okayed as well.

>  - Allow writing only FQDN and be specific in the spec on how we do comparisons and what is left to applications to figure out about how to specify filtering URL patterns.
> - Don't lowercase input from NDEF messages we read, use case-insensitive comparison where the NDEF specs dictate, but expose the unchanged content to web pages/apps.
> - Write input from web pages as it comes (no silent lowercase conversion).

Is that OK? Spec changes come later but you can assume the above for the impl (if you agree).

**Comment by kenchris** [comment]
Can we close?

**Comment by sleevi** [comment]
I'm not sure who that is directed to. I'm used to seeing folks pinged via handle if there's a specific question, and usually see spec text to accompany the proposal to ensure it's clear and unambiguous.

If it was for me, https://github.com/w3c/web-nfc/issues/331#issuecomment-540402533 is not clear to me, and spec changes would be easier for me to make positive contributions. It's hard for me to fathom the implications of the proposal otherwise, but that may be the fact that I'm not working on this, and was just trying to highlight the issues that come up and the impact they might have on the platform.

**Comment by beaufortfrancois** [comment]
@zolkis Can you start a spec PR with https://github.com/w3c/web-nfc/issues/331#issuecomment-540402533 changes?

**Comment by zolkis** [comment]
> Can you start a spec PR with #331 (comment) changes? 

That's already done in #373 (somehow failed to reference it), except that we might need an algorithm for FQDN (or leave that to the implementation, but further improve spec prose about external type validation).

**Comment by beaufortfrancois** [comment]
@zolkis What's left there?

**Comment by zolkis** [comment]
From my part the validate external/local types algorithms address this (to be checked), but we need to fix #350 that is related.

**Comment by zolkis** [comment]
I think this has been fixed by #474 (and #477).
@leonhsl could you please check if we can close this?

**Comment by leonhsl** [comment]
Cool, the algorithms for validating external/local type names look pretty neat now. Thanks @zolkis !

**Comment by zolkis** [comment]
And thanks @kenchris for the comments/help/tips/work on the external type validation.
