### ISSUE TITLE
Write explainer

### ISSUE THREAD

**Issue by beaufortfrancois** [w3c-cg/web-nfc#456]
As this spec will go through another TAG review, we should have an explainer as described at https://w3ctag.github.io/explainers

@kenchris @zolkis Is that something you can write?

**Comment by zolkis** [comment]
We get a lot of questions about scope. 
It's currently NDEF, but there are a lot of use cases for other tech as well.

Thing is, the scope has changed from the original idea of exposing a web-specific projection of NFC.
Since the scope shifted to low level, we need to re-think the key use cases.
At the moment it's NDEF read and write. 

We need to include a plan about adding new features and extending the scope.

We can take the Explainer template section by section and make proposals here.

**Comment by kenchris** [comment]
https://github.com/w3ctag/w3ctag.github.io/blob/master/explainers.md

**Comment by beaufortfrancois** [comment]
Fixed with https://github.com/w3c/web-nfc/pull/469
