### ISSUE TITLE
is it supported in Chrome in pc

### ISSUE THREAD

**Issue by AIB1TAL0S** [w3c-cg/web-nfc#658]
We are currently creating a web app attendance system for our school just wondering if it is supported in most browser

**Comment by anssiko** [comment]
The API is currently implemented in Chrome for Android. If you're interested in the Chrome implementation status, please add ⭐ to https://issues.chromium.org/issues/40431198 to get notified of Chromium project updates for this feature. Even if that bug is marked as fixed, it should get notified if/when there's movement.

This W3C repo is dedicated for discussion on the specification development. For implementation status, you want to follow [chromestatus.com](https://chromestatus.com/feature/6261030015467520) and [caniuse.com](https://caniuse.com/webnfc).

If you are a web developer, you can help bring this API to more platforms by sharing your experiments to raise excitement. See [this demo](https://twitter.com/ChromiumDev/status/1206890116964323328) for an innovative use of this API, for example.

Thank you for your interest.
